# Generated by Django 4.1.2 on 2022-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_gcl', models.CharField(max_length=200)),
                ('nom_juridique', models.CharField(max_length=200)),
                ('siret', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
            ],
        ),
    ]
