# Generated by Django 4.1.2 on 2022-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='tel',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
