# Generated by Django 4.1.2 on 2022-10-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_cabinet_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_interne', models.CharField(max_length=100)),
                ('materiel', models.TextField()),
                ('date_devis', models.DateField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('cabinet_facturation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='achats.cabinet')),
                ('cabinet_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='achats.cabinet')),
            ],
        ),
    ]
