# Generated by Django 4.1.2 on 2022-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='commentaire',
            field=models.CharField(default='---', max_length=300),
        ),
    ]
